import Head from 'next/head';
import Link from 'next/link';
const about = '/about';
export default function Home() {
  return (
    <>
      <Head>
        <title>Next-Demo App testing</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='demoPageView'>
        <h1> home page</h1>
        <div className='link'>
          <Link href={about}>About</Link>
          <Link href='/portfolio'>Portfolio</Link>
        </div>
      </div>
    </>
  );
}
